version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realestate
    ports:
      - "5432:5432"

  listing-service:
    build: ./listing-service
    ports:
      - "9001:9000"
    depends_on:
      - kafka
      - zookeeper
      - postgres

  notification-service:
    build: ./notification-service
    ports:
      - "9002:9000"
    depends_on:
      - kafka
      - zookeeper
      - postgres

  graphql-service:
    build: ./graphql-service
    ports:
      - "9000:9000"
    depends_on:
      - listing-service
      - notification-service
